---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fleet.fleetrollout.io
  resources:
  - fleetrollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fleet.fleetrollout.io
  resources:
  - fleetrollouts/finalizers
  verbs:
  - update
- apiGroups:
  - fleet.fleetrollout.io
  resources:
  - fleetrollouts/status
  verbs:
  - get
  - patch
  - update
