//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetRollout) DeepCopyInto(out *FleetRollout) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetRollout.
func (in *FleetRollout) DeepCopy() *FleetRollout {
	if in == nil {
		return nil
	}
	out := new(FleetRollout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetRollout) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetRolloutList) DeepCopyInto(out *FleetRolloutList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FleetRollout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetRolloutList.
func (in *FleetRolloutList) DeepCopy() *FleetRolloutList {
	if in == nil {
		return nil
	}
	out := new(FleetRolloutList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FleetRolloutList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetRolloutSpec) DeepCopyInto(out *FleetRolloutSpec) {
	*out = *in
	in.TargetSelector.DeepCopyInto(&out.TargetSelector)
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	out.WaveSize = in.WaveSize
	if in.HealthGate != nil {
		in, out := &in.HealthGate, &out.HealthGate
		*out = new(HealthGate)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetRolloutSpec.
func (in *FleetRolloutSpec) DeepCopy() *FleetRolloutSpec {
	if in == nil {
		return nil
	}
	out := new(FleetRolloutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetRolloutStatus) DeepCopyInto(out *FleetRolloutStatus) {
	*out = *in
	if in.LastGood != nil {
		in, out := &in.LastGood, &out.LastGood
		*out = new(LastGood)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollback != nil {
		in, out := &in.Rollback, &out.Rollback
		*out = new(RollbackStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(RolloutPlan)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetRolloutStatus.
func (in *FleetRolloutStatus) DeepCopy() *FleetRolloutStatus {
	if in == nil {
		return nil
	}
	out := new(FleetRolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthGate) DeepCopyInto(out *HealthGate) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthGate.
func (in *HealthGate) DeepCopy() *HealthGate {
	if in == nil {
		return nil
	}
	out := new(HealthGate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastGood) DeepCopyInto(out *LastGood) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastGood.
func (in *LastGood) DeepCopy() *LastGood {
	if in == nil {
		return nil
	}
	out := new(LastGood)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollbackStatus) DeepCopyInto(out *RollbackStatus) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollbackStatus.
func (in *RollbackStatus) DeepCopy() *RollbackStatus {
	if in == nil {
		return nil
	}
	out := new(RollbackStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RolloutPlan) DeepCopyInto(out *RolloutPlan) {
	*out = *in
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EvaluatingWave != nil {
		in, out := &in.EvaluatingWave, &out.EvaluatingWave
		*out = new(int32)
		**out = **in
	}
	if in.GateStartedAt != nil {
		in, out := &in.GateStartedAt, &out.GateStartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RolloutPlan.
func (in *RolloutPlan) DeepCopy() *RolloutPlan {
	if in == nil {
		return nil
	}
	out := new(RolloutPlan)
	in.DeepCopyInto(out)
	return out
}
